baseURL = "http://oliverscheer.github.io/"
languageCode = "en-us"
title = "Oliver Scheer"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
math = false 


[params]
  author = "Oliver Scheer"
  description = "Homepage, docs, cheat sheets, links, etc."
  [params.footer]
    text = "By Oliver Scheer"
    url = "https://oliverscheer.github.io"

[permalinks]
    "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  
[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files